// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvBhG9c87t2b6Qdk_XBwXK4q3DCgsYTyU',
    appId: '1:245756951177:web:2374c685c3af4f8eb6a458',
    messagingSenderId: '245756951177',
    projectId: 'firestore-user-info',
    authDomain: 'firestore-user-info.firebaseapp.com',
    storageBucket: 'firestore-user-info.firebasestorage.app',
    measurementId: 'G-WXY10RY3BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOKMnJY9QQQUUbyBAeIbwFbHfXyNcNHJQ',
    appId: '1:245756951177:android:94d3ff09999f34b3b6a458',
    messagingSenderId: '245756951177',
    projectId: 'firestore-user-info',
    storageBucket: 'firestore-user-info.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBh-2QT_fFsS4909rtQ6-n0ignKnvI8N4',
    appId: '1:245756951177:ios:c2912162d3ef5d94b6a458',
    messagingSenderId: '245756951177',
    projectId: 'firestore-user-info',
    storageBucket: 'firestore-user-info.firebasestorage.app',
    iosBundleId: 'com.example.firestoreUserInfo',
  );
}
